// "use client";
import './globals.css'
import { Inter } from 'next/font/google'
import '/styles/globals.css'
import { useEffect } from 'react'
import type { AppProps } from 'next/app'
import { MantineProvider } from '@mantine/core'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import axios from 'axios'


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Nest/Next Lean App',
  description: 'Generated by create next app',
}
// const queryClient = new QueryClient({
//   defaultOptions: {
//     queries: {
//       retry: false,
//       refetchOnWindowFocus: false,
//     },
//   },
// })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // axios.defaults.withCredentials = true
  // useEffect(() => {
  //   console.log('RootLayout useEffect')
  //   const getCsrfToken = async () => {
  //     const { data } = await axios.get(
  //       `${process.env.NEXT_PUBLIC_API_URL}/auth/csrf`
  //     )
  //     axios.defaults.headers.common['csrf-token'] = data.csrfToken
  //   }
  //   getCsrfToken()
  // }, [])
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
